[Service]
Environment=PHYTO_HTTPS_PORT=443
Environment=PHYTO_TLS_CERT_FILE=/etc/phyto/tls/server.crt
Environment=PHYTO_TLS_KEY_FILE=/etc/phyto/tls/server.key
AmbientCapabilities=
AmbientCapabilities=CAP_SYS_ADMIN CAP_SYS_RAWIO CAP_NET_BIND_SERVICE
